### ISSUE TITLE
incorrect brain.start metadata for recurring events

### ISSUE THREAD

**Issue by gyst** [plone/plone.app.event#117]
A lot of the work I've done in #114 works around the basic issue that while DateRecurringIndex indexes a set of start dates, the returned metadata always contain the start date of the first occurrencce.

If you do a get_events query with a start/end filter, you'd expect the resulting catalog result to adequately reflect the start/end of the next occurrence. So if you search for only future events you definitely do not want to have a brain.start which falls in the past in your search results.

Because brain.start does not correctly reflect the first upcoming occurrence it becomes very difficult to handle get_events results correctly without expanding all occurrences.

**Comment by jensens** [comment]
outdated
