### ISSUE TITLE
Various issues with plone.app.event 1.2

### ISSUE THREAD

**Issue by zopyx** [plone/plone.app.event#147]
We are using plone.app.event 1.2 with Dexterity and Plone 4.3.2 in a migration project.
start and end dates are generated during from DateTime instances using

start = datetime.fromtimestamp(start_date_old.timeTime()
....

The @@edit view of the related event instances works.
Trying to save an event fails with this:

2014-03-07 09:03:54 ERROR Zope.SiteErrorLog 1394179434.560.952354709109 http://dev1.veit-schiele.de:5080/eteaching/news/tagungen/ilias_2008/@@edit
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module plone.z3cform.layout, line 66, in **call**
  Module plone.z3cform.layout, line 50, in update
  Module plone.dexterity.browser.edit, line 54, in update
  Module plone.z3cform.fieldsets.extensible, line 59, in update
  Module plone.z3cform.patch, line 30, in GroupForm_update
  Module z3c.form.group, line 141, in update
  Module plone.app.z3cform.csrf, line 21, in execute
  Module z3c.form.action, line 98, in execute
  Module z3c.form.button, line 315, in **call**
  Module z3c.form.button, line 170, in **call**
  Module plone.dexterity.browser.edit, line 25, in handleApply
  Module z3c.form.group, line 97, in extractData
  Module z3c.form.group, line 64, in extractData
  Module z3c.form.form, line 146, in extractData
  Module z3c.form.field, line 324, in extract
  Module z3c.form.field, line 216, in validate
  Module z3c.form.validator, line 201, in validate
  Module z3c.form.validator, line 206, in validateObject
  Module zope.interface.interface, line 590, in validateInvariants
  Module plone.app.event.dx.behaviors, line 141, in validate_start_end
  Module z3c.form.validator, line 175, in **getattr**
  Module z3c.form.datamanager, line 71, in get
  Module plone.app.event.dx.behaviors, line 342, in start
  Module plone.app.event.dx.behaviors, line 399, in _prepare_dt_get
AttributeError: timezone

Calling the default view of an event fails with this:

2014-03-07 09:09:12 ERROR Zope.SiteErrorLog 1394179752.30.182035064437 http://dev1.veit-schiele.de:5080/eteaching/news/tagungen/ilias_2008/event_view
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module Products.Five.browser.metaconfigure, line 479, in **call**
  Module Products.Five.browser.pagetemplatefile, line 125, in **call**
  Module Products.Five.browser.pagetemplatefile, line 59, in **call**
  Module zope.pagetemplate.pagetemplate, line 132, in pt_render
  Module zope.pagetemplate.pagetemplate, line 240, in **call**
  Module zope.tal.talinterpreter, line 271, in **call**
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 888, in do_useMacro
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 954, in do_defineSlot
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 858, in do_defineMacro
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 954, in do_defineSlot
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 954, in do_defineSlot
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 946, in do_defineSlot
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 858, in do_defineMacro
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 620, in do_insertText_tal
  Module Products.PageTemplates.Expressions, line 225, in evaluateText
  Module zope.tales.tales, line 696, in evaluate
- URL: /home/ajung/.buildout/eggs/plone.app.event-1.2-py2.7.egg/plone/app/event/browser/event_view.pt
- Line 19, Column 6
- Expression: <PathExpr standard:u'data/start/isoformat'>
- Names:
    {'args': (),
     'container': <Event at /eteaching/news/tagungen/ilias_2008>,
     'context': <Event at /eteaching/news/tagungen/ilias_2008>,
     'default': <object object at 0x7ff3f25f3b80>,
     'here': <Event at /eteaching/news/tagungen/ilias_2008>,
     'loop': {},
     'nothing': None,
     'options': {},
     'repeat': <Products.PageTemplates.Expressions.SafeMapping object at 0x7ff3d6cf6cb0>,
     'request': <HTTPRequest, URL=http://dev1.veit-schiele.de:5080/eteaching/news/tagungen/ilias_2008/event_view>,
     'root': <Application at >,
     'template': <Products.Five.browser.pagetemplatefile.ViewPageTemplateFile object at 0x7ff3d64ebdd0>,
     'traverse_subpath': [],
     'user': <PropertiedUser 'admin'>,
     'view': <Products.Five.metaclass.SimpleViewClass from /home/ajung/.buildout/eggs/plone.app.event-1.2-py2.7.egg/plone/app/event/browser/event_view.pt object at 0x7ff3d6b46090>,
     'views': <Products.Five.browser.pagetemplatefile.ViewMapper object at 0x7ff3d6b4fc90>}
  Module zope.tales.expressions, line 217, in **call**
  Module Products.PageTemplates.Expressions, line 147, in _eval
  Module zope.tales.expressions, line 124, in _eval
  Module Products.PageTemplates.Expressions, line 97, in trustedBoboAwareZopeTraverse
  Module zope.traversing.adapters, line 136, in traversePathElement
- **traceback_info**: (None, 'isoformat')
  Module zope.traversing.adapters, line 50, in traverse
- **traceback_info**: (None, 'isoformat', [])
  LocationError: (None, 'isoformat')

The instance dict of an event looks like this

> > > pprint.pprint( app.eteaching.news.tagungen.ilias_2008.**dict**)
> > > {'_Access_contents_information_Permission': ('Manager',
> > >                                              'Owner',
> > >                                              'Editor',
> > >                                              'Reader',
> > >                                              'Contributor',
> > >                                              'Site Administrator'),
> > >  '_Change_portal_events_Permission': ('Manager',
> > >                                       'Owner',
> > >                                       'Editor',
> > >                                       'Site Administrator'),
> > >  '_Modify_portal_content_Permission': ('Manager',
> > >                                        'Owner',
> > >                                        'Editor',
> > >                                        'Site Administrator'),
> > >  '_View_Permission': ('Manager',
> > >                       'Owner',
> > >                       'Editor',
> > >                       'Reader',
> > >                       'Contributor',
> > >                       'Site Administrator'),
> > >  '__ac_local_roles__': {'crenz': ('Owner',)},
> > >  '**provides**': <zope.interface.Provides object at 0x8b0b090>,
> > >  '_owner': (['eteaching', 'acl_users'], 'crenz'),
> > >  '_plone.uuid': '1e735a0ea694470eb532efd691da0dc1',
> > >  'cmf_uid': <Products.CMFUid.UniqueIdAnnotationTool.UniqueIdAnnotation object at 0x8b07aa0>,
> > >  'contact_email': '',
> > >  'contact_name': '',
> > >  'contact_phone': '',
> > >  'creation_date': DateTime('2014/03/07 08:50:32.752047 GMT+1'),
> > >  'creators': (u'crenz', 'admin'),
> > >  'description': 'Die 7. Internationale ILIAS-Konferenz findet gemeinsam mit dem Fernausbildungskongress der Bundeswehr an der Helmut-Schmidt-Universit\xc3\xa4t in Hamburg statt.',
> > >  'end': datetime.datetime(2008, 9, 10, 17, 0),
> > >  'id': 'ilias_2008',
> > >  'location_id': 0,
> > >  'modification_date': DateTime('2014/03/07 08:50:32.968889 GMT+1'),
> > >  'portal_type': 'Event',
> > >  'start': datetime.datetime(2008, 9, 9, 9, 0),
> > >  'title': '7. Internationale ILIAS Konferenz 2008',
> > >  'version_id': 0,
> > >  'workflow_history': {'simple_publication_workflow': ({'action': None, 'review_state': 'private', 'actor': 'admin', 'comments': '', 'time': DateTime('2014/03/07 08:50:32.757447 GMT+1')}, {'action': None, 'review_state': 'visible', 'actor': None, 'comments': 'Setting state to visible', 'time': DateTime('2014/03/07 08:50:32.962604 GMT+1')})}}

**Comment by djowett** [comment]
Was this resolved in 1.1.x branch?  I'm getting this issue after using p.a.contenttypes migrator
