### ISSUE TITLE
move translations to plone domain and maybe even plone.app.locales

### ISSUE THREAD

**Issue by thet** [plone/plone.app.event#181]
Recently I had the impression that having the translations under the "plone" domain would avoid some translation bug confusion, which I had. So I propose to move the translations to the plone domain and remove the plone.app.event domain.
Cons: overriding templates which declare the plone.app.event domain will break, so this change must be - as always - clearly documented.

Maybe we should even move the translations files to plone.app.locales. Translators are using this and usaly don't care about other packages.

I would change this for plone.app.event 2.0 and just document the changes and not include old translations files for BBB compatibility to keep the package clean.

@vincentfretin @polyester @svx - any opinions about that?

**Comment by vincentfretin** [comment]
If plone.app.event 2.0 is for Plone 5 only, we can indeed move to plone domain in plone.app.locales master.
The steps to accomplish this if you want to do it are the following:

- modify the plone.app.event code to use the plone domain
- modify experimental/i18n.cfg in buildout.coredev 5.0 to include plone.app.event in the plone domain.
- bin/buildout -c experimental/i18n.cfg
- modify your local zope.tal to be able to extract messages from templates that use tal:attributes chameleon functionality (see the top of experimental/i18n.cfg). If you don't do it, you will have messages removed.
- use
  bin/i18n plone
  to regenerate plone.pot and resync plone files.
- You can then use "i18ndude admix" command to transfer translated messages from plone.app.event.po to plone.po for each language.

**Comment by thet** [comment]
@vincentfretin thanks for this explanation!
Actually, plone.app.event is also Plone 4.3 compatible (via some BBB helpers) and should stay that way. What's the reason, that moving to the plone domain would be a problem with Plone 4.3? Because we cannot move the message strings to the 4.3 part of plone.app.locales? If so, i'd only change the domain to ``plone`` but leave the translations files in plone.app.event.

**Comment by vincentfretin** [comment]
It's not a problem, you can do it for Plone 4.3, there is a plone.app.locales 4.3.x branch.

**Comment by vincentfretin** [comment]
We should do that for plone.app.discussion too
https://github.com/plone/plone.app.discussion/issues/66

**Comment by thet** [comment]
also plone.app.dexterity https://github.com/plone/plone.app.dexterity/issues/158

**Comment by thet** [comment]
We have to postpone that for plone.app.event 2.1, as plone.app.event 2.0 is already part of Plone 5.
