### ISSUE TITLE
Refactoring: merge with plone.app.contenttypes

### ISSUE THREAD

**Issue by thet** [plone/plone.app.event#188]
Separating plone.app.event from plone.app.contenttypes did make sense: until 2.0 it contained Archetypes based Event type and Dexterity based behaviors, and this package is older than plone.app.contenttypes.

Since Archetypes support was removed with 2.0 we could merge plone.app.event into plone.app.contenttypes and simplify Plones dependency hell.

By the way, the event accessor pattern can also be removed, because that was only to support Archetypes and Dexterity with the same codebase.
And plone.event should be renamed to something not assuming to deal with an event notification system. Maybe plone.calendaring would be a better name.

Refer to this discussion: https://github.com/plone/Products.CMFPlone/issues/570

**Comment by thet** [comment]
@tisto ^^ :)

**Comment by tisto** [comment]
+1

**Comment by pbauer** [comment]
:+1:

**Comment by thet** [comment]
not happening. unless someone wants to work on that.
