### ISSUE TITLE
Do not create write-on-read

### ISSUE THREAD

**Issue by jensens** [plone/plone.app.event#191]
in 
https://github.com/plone/plone.app.event/blob/master/plone/app/event/portlets/portlet_events.py#L148
a write on read is created, because memoize instance writes to the DB. This may lead to transaction conflicts and prevents from mounting a DB R/O

Better use memoize ram here.

**Comment by thet** [comment]
done with https://github.com/plone/plone.app.event/commit/34b8387c86cd6910560f3709e4e1559ceda0389c
I changed it to plone.memoize.view caching, like the result caching in plone.app.event.browser.event_listing.
This should be rethought - caching on memoize ram with a good cache key would be more effective, and ideally the portlet is called only once per request, so the caching on the request is might be pointless.
