### ISSUE TITLE
expand_event limits events instead of expanding them

### ISSUE THREAD

**Issue by frisi** [plone/plone.app.event#261]
passing an event without recurrences to expand_events should not affect the event.

currently a call to expand_events removes an event if it starts after the limit provided to expand_events.

it is ok, that occurrences of an event after the limit are not returned (for performance reasons) but plain events should survive.
usecase: event-index of a portal. we limit recurrences to today+365days, but want to show events happening next year too.

```python
>>> from plone.app.event.base import RET_MODE_OBJECTS
>>> from plone.app.event.base import expand_events
>>> from datetime import timedelta
>>> from datetime import datetime

>>> event.start_date
datetime.datetime(2018, 8, 11, 15, 0, tzinfo=<DstTzInfo 'Europe/Vienna' CEST+2:00:00 DST>)

no end-given - event is returned
>>> expand_events([event],RET_MODE_OBJECTS,start=datetime.now())
[<Event at /Plone/testevent>]

limiting occurences, also removes the plain event:
>>> expand_events([event],RET_MODE_OBJECTS,start=datetime.now(), end=datetime.now()+timedelta(365))
[]
```

**Comment by frisi** [comment]
i'd really like to hear your opinion on that @thet 

iiuc the usecase expand_events is supposed to support is

```python
# find events matching my criteria (some of them possibly 2 years in the future)
brains = api.content.find(...)

# also include occurences of recurring events
# but limit expanding to one year
expand_events(brains,RET_MODE_OBJECTS,start=datetime.now(), end=datetime.now()+timedelta(365))

# THIS should not remove "pure" events with enddate >= today+365 from the list
```

**Comment by thet** [comment]
I agree.
I looked into the usage of expand_events - everywhere a catalog search is done first which limits the results in the given timespan anyways. So I do not expect the core functionality to behave any different.
