### ISSUE TITLE
event_icon.png in css

### ISSUE THREAD

**Issue by ewohnlich** [plone/plone.app.event#283]
Our broken link checker found a broken link in event.css, with the very first rule referencing "event_icon.png". This renders as ${portal_url}/event_icon.png when it should be ${portal_url}/++resource++plone.app.event/event_icon.png. However, I don't think this rule is even needed at all - maybe get rid of it?

**Comment by thet** [comment]
You're right, tnx for reporting.
Fixed in https://github.com/plone/plone.app.event/pull/284

You may review the PR, even if you're not part of the @plone-foundation org.
