### ISSUE TITLE
Update structured data schema

### ISSUE THREAD

**Issue by 1letter** [plone/plone.app.event#312]
The templates, wich use "structured data schemas"  should be update until 04/2020.
more info: [google announcement](https://webmasters.googleblog.com/2020/01/data-vocabulary.html)

**Comment by thet** [comment]
thanks for bringing this up!

**Comment by 1letter** [comment]
i would like to work on it during the sprint "[plonetagung 2020](https://plonetagung.de/2020/)", if nobody has done it before.
