### ISSUE TITLE
Still uses plone-legacy bundle

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/plone.app.event#350]
`plone.app.event` still tries to add a resource to the `plone-legacy` bundle. It in fact creates this bundle. I have no idea if this is still needed. At first glance things still work, but I am not sure what to check.
@pbauer already removed this in January, but then [reverted it](https://github.com/plone/plone.app.event/commit/ed59dc525f66fba0dafa485f94515a30cb04af86).

See also [my comment in the ES6 upgrade PR](https://github.com/plone/plone.app.upgrade/pull/269#issuecomment-1077461240).

Slightly related, there are some javascript test directories that have not been touched in 11 years:

- https://github.com/plone/plone.app.event/tree/master/plone/app/event/tests/javascripts
- https://github.com/plone/plone.app.event/tree/master/plone/app/event/tests/qunit 

Maybe these can be removed as well?

**Comment by petschki** [comment]
I'll fix that today

**Comment by thet** [comment]
@petschki let's talk about that - to get the same functionality like before I'd love to have here a combination of pat-date-picker (which needs to be fixed) and pat-depends.

I just did something very similar for a client project, which depends on the plone.app.z3cform plone-2150 branch.

This is the JS I came up with (should be obsolete, if pat-date-time-picker supports the same dependency setting as pat-date-picker and with some pat-depends):

```
  function is_valid_date(date) {
    // https://stackoverflow.com/a/1353711/1337474
    return date instanceof Date && !isNaN(date);
  }

  function add_hours(date, hours) {
    // https://stackoverflow.com/a/1050782/1337474
    date.setTime(date.getTime() + hours * 60 * 60 * 1000);
    return date;
  }

  function set_date(el, isostring) {
    var date = new Date(isostring); // change to Date to enforce datetime isostrings.
    if (!is_valid_date(date)) {
      return;
    }
    isostring = date.toISOString();
    if (el.type === "date") {
      el.value = isostring.split("T")[0];
    } else if (el.type === "datetime-local") {
      el.value = isostring.split(".")[0];
    }
  }

  var event_edit__open_end = document.querySelector("input[name='form.widgets.IEventBasic.open_end:list'], input[name='form.widgets.IEventBasicNonRequired.open_end:list']"); // prettier-ignore
  var event_edit__whole_day = document.querySelector("input[name='form.widgets.IEventBasic.whole_day:list'], input[name='form.widgets.IEventBasicNonRequired.whole_day:list']"); // prettier-ignore
  var event_edit__start = document.querySelector("[name='form.widgets.IEventBasic.start'], [name='form.widgets.IEventBasicNonRequired.start']"); // prettier-ignore
  var event_edit__end = document.querySelector("[name='form.widgets.IEventBasic.end'], [name='form.widgets.IEventBasicNonRequired.end']"); // prettier-ignore

  var start_val;
  var end_val;

  if (event_edit__start) {
    event_edit__start.addEventListener("change", function () {
      start_val = event_edit__start.value;
      end_val = event_edit__end.value;
      var _start = new Date(start_val);
      var _end = new Date(end_val);
      if (!is_valid_date(_end) || _end < _start) {
        _end = _start;
        _end = add_hours(_end, 1);
        end_val = _end.toISOString();
        set_date(event_edit__end, end_val);
      }
    });
  }

  if (event_edit__open_end) {
    event_edit__open_end.addEventListener("input", function () {
      if (event_edit__open_end.checked) {
        $(event_edit__end).hide();
      } else {
        $(event_edit__end).show();
      }
    });
  }

  if (event_edit__whole_day) {
    event_edit__whole_day.addEventListener("input", function () {
      start_val = event_edit__start.value;
      end_val = event_edit__end.value;
      if (event_edit__whole_day.checked) {
        event_edit__start.type = "date";
        event_edit__end.type = "date";
      } else {
        event_edit__start.type = "datetime-local";
        event_edit__end.type = "datetime-local";
      }
      set_date(event_edit__start, start_val);
      set_date(event_edit__end, end_val);
    });
  }
```

**Comment by petschki** [comment]
thanks! I gave your script a try and it's almost there ... multiple clicking on "open end" decreases the date by 1 day and "open end" should hide the whole container, but I can fix that.

Main question: for simplification I just made a new `plone.bundles/eventedit` and registered it in the new resourceregistry ... I think that's the simplest way instead of wiring it up in mockup ... what do you think?

the `plone.bundles/plone-legacy` and old `plone.resources/plone-app-event` parts get removed by `plone.app.upgrade` so there's no need for an upgrade step here ...

**Comment by petschki** [comment]
day decreasing on "whole day" click is because of missing timezone offsets ... `toISOString` is always UTC 🤦🏼‍♂️

https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString

**Comment by thet** [comment]
plone.bundles/eventedit - I, sounds good and is at the same time a example on how to integrate javascript in the resource registry. that should probably only for logged-in users, right?

timezone offsets: oh-no...
in the worst case we have to build a JavaScript function to construct the ISO string as timezone-naive, if there is no official API...

what do you think about the pat-datetime-picker and pat-depends way?

**Comment by petschki** [comment]
I've solved it like this

https://github.com/plone/plone.app.event/blob/e2b80c895478cd267e94e9ebf3f3ea3712dccac5/plone/app/event/browser/resources/event.js#L6-L10

PR here #353
