### ISSUE TITLE
SearchableText indexer is never called

### ISSUE THREAD

**Issue by petschki** [plone/plone.app.event#363]
Since the implementation of `collective.textindexer` into `plone.app.dexterity` https://github.com/plone/plone.app.dexterity/pull/344 the `SearchableText` indexer here never gets called. My suggestion would be to remove it here in order to avoid confusion when someone wants to override the indexer.

**Comment by davisagli** [comment]
@petschki Huh? It was already removed: https://github.com/plone/plone.app.event/pull/354

**Comment by petschki** [comment]
Oh my ... thank you @davisagli ... I've figured out, that I've checked out my recurring event fixture branch #349 which was not rebased on the current master. Did that and all works as expected. Sorry for the noise 🫣
