### ISSUE TITLE
Google calendar link in Event (event_view) 

### ISSUE THREAD

**Issue by aormazabal** [plone/plone.app.event#364]
Hey @plone/developers!

I'm think contributing in this repo adding a link to add plone Event in Google calendar. It would be placed in event_view.

It's something simple like put a link next to ICal link with this href=
https://www.google.com/calendar/render?action=TEMPLATE&text=${data/title}&details=${data/description}&location=${data/location}&dates=${data_start_gcal}%2F${data_end_gcal}&ctz=${data/start/tzinfo/zone}

ICal link needs to be downloaded and then opened.  However a Google calendar link will be useful because many people use Google Calendar and with a simple click you can add it. Besides this will still function in desktop devices also.

What do you think? Can I contribute with this feature in branches 3.2.x and master?

![imagen](https://user-images.githubusercontent.com/2027765/212112642-dc16c9a0-e9bf-4ac5-abd7-9ce62a6b1185.png)

**Comment by mtrebron** [comment]
I would be wary of supporting any particular vendor with a specific implementation. This kind of enhancement would be something an integrator could do.

**Comment by stevepiercy** [comment]
I agree with @mtrebron. Google Calendar is not an open standard, .ical is.

I think this would be a nice recipe, though. Even if this proposal does not make it into this project, I would support adding this as a "how to" for modifying a content type in documentation. It would go somewhere in here: https://6.docs.plone.org/backend/content-types.html. Clearly that section needs some love.

**Comment by frapell** [comment]
Maybe having a setting in the control panel to enable/disable the feature? I see value in having something like this included by default... Just my 2c...

**Comment by stevepiercy** [comment]
> Maybe having a setting in the control panel to enable/disable the feature?

I like that idea. Either as a setting or a recipe, I would use this for at least one of my clients.

**Comment by tiberiuichim** [comment]
There's already support in Plone for Google Translation API. See https://classic.demo.plone.org/@@language-controlpanel#autotoc-item-autotoc-2 where there's a field "Google Translation API Key
Is a paying API in order to use google translation service"

![image](https://user-images.githubusercontent.com/141568/212247512-13fd38d8-d204-4e7d-8cb8-25f59c371dce.png)

**Comment by aormazabal** [comment]
So, Are you still disagree or not? 
We can put the link if we put a boolean in control panel to decide if we show the link, by default not showed.
Have I understood it correctly?

**Comment by stevepiercy** [comment]
@aormazabal I think @tiberiuichim is saying that there is precedent in Plone to use Google stuff. [Checking PyPI, I count 1,193 Plone projects with Google stuff](https://pypi.org/search/?q=google&o=&c=Framework+%3A%3A+Plone).

@mtrebron if this were a configurable option in its control panel, would it be acceptable to you? Or would it be OK to make it always present?

**Comment by mtrebron** [comment]
@tiberiuichim @stevepiercy the support for Google Translate is a setting in the backend that site administrators can enable, while the feature suggested by @aormazabal would be displayed on the page as seen by editors / visitors. 

I believe the distinction is important. Also, the feature in our language controlpanel comes from a time where a) G was the only game in town, and b) there was less controversy over how Google's handles personal data. Similar with the ability to insert a G analytics snippet (even though the foundation now uses Matomo). This leads me to a third issue: having to maintain yet another "embrace and extend" third party standard which may possibly change over time.

Also notice that the PyPi list includes many packages in the collective. In my opinion, the collective is a perfect place for customizations that integrators may want to use. See for example recaptcha and hCaptcha support. 

Conclusion: a) nice idea if not enabled by default and config in the backend. b) even nicer idea if offered separately in a package in the collective. Also agree that it could be used as a documentation example.

**Comment by aormazabal** [comment]
Ok, I see the reasons. Maybe is better to continue overriding the summary_event template to offer this feature.

Thanks!
