### ISSUE TITLE
Need to remove leading zeros in day of month and in hour for 12 hour format

### ISSUE THREAD

**Issue by dthomas218** [plone/plone.app.event#45]
I don't know if this is the right place to post this but Plone's use of Jan. 01 01:59 am does not conform to American (or British?) usage. 

The strftime function supports %e (day of month without leading zero) and %l (hour without leading zero) but in plonelocales.po they do not work as substitutes, for example, ${e} for ${d}. 

The strptime funtion will remove zeroes automatically, AFAIK.

**Comment by eduardogoncalves** [comment]
What about to use 'format' method?

```
>>> import datetime
>>> import locale
>>> locale.setlocale( locale.LC_TIME, ‘pt_BR.utf8’ )
>>> ‘{dt.day} de {dt:%B} de {dt.year}’.format(dt = datetime.datetime.now())
‘3 de junho de 2018’
```

source: [https://www.saibatudomt.com.br/2018/06/python-strftime-date-without-leading-0.html](https://www.saibatudomt.com.br/2018/06/python-strftime-date-without-leading-0.html)
